### ISSUE TITLE
/airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError) airvpn_1  

### ISSUE THREAD

**Issue by Poltergeisen** [oblique/dockerfiles#6]
Trying to connect to airvpn and I'm getting this error:
```
Attaching to docker_airvpn_1
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'
airvpn_1       | Mode: udp
airvpn_1       | /airvpn.rb:98:in `select_config': undefined method `[]' for nil:NilClass (NoMethodError)
airvpn_1       |        from /airvpn.rb:138:in `<main>'

```

This is the relevant section of my compose file:
```
services:
  airvpn:
    image: oblique/airvpn
    ports:
      - 1080:1080
    cap_add:
      - net_admin   
    restart: always
    environment:
      - COUNTRY=us
      - MODE=udp-443
    volumes:
      - "./airvpn:/airvpn"
    networks:
      - http_network
```

I went to the openvpn config generator in the airvpn website and selected all configs in the US. Then went to advanced and selected all protocols in the list. Not sure what im missing here with this container, but hoping it doesn't have anything to do with the networks since deluge is behind a reverse proxy

**Comment by Poltergeisen** [comment]
![image](https://user-images.githubusercontent.com/44731113/83705128-b1575b80-a5d9-11ea-8fe3-883fc0b8391d.png)
This is my airvpn folder as well
